jdk: oraclejdk8
language: android
android: 

components: 
  - tools # to get the new repo
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install: 
  - "chmod +x gradlew"

directories: 
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script: 
  - "./gradlew build connectedCheck --stacktrace"
