language: android

branches:
  only:
    - master

env:
  global:
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2

components:
      - platform-tools
      - tools
      - build-tools-25.0.2
      - android-25
      - extra-android-m2repository
      - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

jdk:
  - oraclejdk8
 
before_install:
 - chmod +x gradlew

before_script:
	# Create and start emulator
    - ./gradlew build jacocoTestReport assembleAndroidTest
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator

script: 
   - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
   - ./gradlew build connectedCheck
