language: android

branches:
  only:
    - master

android:
  components:
      - platform-tools
      - tools
      - build-tools-25.0.0
      - android-25
      - extra-android-m2repository
      
jdk:
  - oraclejdk8
 
before_install:
 - chmod +x gradlew
 
script: 
   - ./gradlew build connectedCheck
